      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: sftp  # Ajoutez cette ligne
          port: 22        # Changez le port 21 pour le 22 (port SFTP)
          server-dir: ./
